### ISSUE TITLE
Thanks a ton. I'm going to be playing with this a lot.

### ISSUE THREAD

**Issue by elorest** [NeuraLegion/blue_cr#1]

**Comment by bararchy** [comment]
@elorest Enjoy :) 
I'm gonna add more stuff in the next few days so keep an eye on things, when this will be ready I'll try to create a keyboard control for my parrot drone ;)

**Comment by elorest** [comment]
I'm going to need to use bluez primarily for audio applications,
specifically in a vehicle infotainment system. Have been playing with bluez
and writing some of my own simple wrappers.

Looks like this could be really useful moving forward though. It's really
cool what you guys are doing with Crystal. My company is also using quite a
bit of crystal. I'm also on the core team of Amber framework.

**Comment by Xosmond** [comment]
Hey guys have you used this shard only on linux or Mac too? I tried to use dbus on Mac but I couldn't.

**Comment by bararchy** [comment]
@Xosmond I only tried on Linux, can you tell me what issues you had? 
I didn't even know Mac had a Dbus interface

**Comment by bararchy** [comment]
@elorest thanks :) 
We really try to push everything we can as an OS project.
Happy you find it useful

**Comment by elorest** [comment]
@bararchy What bluez docs are you basing this off of. Do you know if it's possible to set up bluetooth audio through dbus. I've been sort of going down the path of creating a wrapper for libbluetooth.

**Comment by bararchy** [comment]
@elorest I mostly used https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc and QTdbusViewer to explore the structure of objects. 

The Dbus API is (AFAIK) covering 100% Bluez functionality, so if Bluez can do it, so can Dbus

**Comment by Xosmond** [comment]
@bararchy Oh I got dbus working fine on Mac with Macports, which is great, but bluez is linux specific software. By the way, this is a good start. 

PD: I was trying to figure out how to communicate with bluetooth via blued process on Mac but I'am not an expert so I got stuck.

**Comment by elorest** [comment]
@bararchy Have you written anything where you pair through dbus? I tried this but it seems that there's a response required that I never get prompted for. 
`device.interface.call("Pair").reply`

**Comment by bararchy** [comment]
@elorest Looking at the code I don't think I ever got to the "Pair" part, as we really needed BLE and not standard bluetooth functionality the "connect" was enough for us.

If you manage to get some error message send it here and I'll try to help

**Comment by elorest** [comment]
I've just been putting my phone into broadcast mode, and then trying to pair with it using `device.interface.call("Pair").reply`. It pops a message up on the phone that it failed because pairing code didn't match. It gives a similar message on the crystal/dbus side without every prompting for a code or confirmation.

If I pair from `bluetoothctl` it makes me compare a number on my phone with one that shows up in the CLI. If you don't mind just try that really fast with your phone and see if you have any ideas. I know you spent quite a bit of time looking at the bluez dbus code a year ago.

Thanks a lot. Also it's Hacktoberfest so PR's will get you a cool tshirt. :)
https://hacktoberfest.digitalocean.com/

**Comment by elorest** [comment]
This looks interesting. https://gist.github.com/studiofuga/249035dd86e1c7c7bb75

**Comment by bararchy** [comment]
@elorest Have you managed to fix it?
